{{- if .Values.grafana.enabled }}
{{- if .Values.vlogxy.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .Release.Name }}-logs
  namespace: {{ .Release.Namespace }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: kof-logs
    type: victoriametrics-logs-datasource
    access: proxy
    {{- if .Values.kcm.kof.acl.enabled }}
    url: http://{{ .Release.Name }}-kof-acl:{{ .Values.kcm.kof.acl.port }}/vlogxy
    {{- else if .Values.vlogxy.enabled }}
    url: http://{{ .Release.Name }}-vlogxy:{{ .Values.vlogxy.service.servicePort }}
    {{- else }}
    url: http://kof-storage-victoria-logs-cluster-vlselect:9471
    {{- end }}
    isDefault: true
    jsonData:
      timeInterval: "5s"
    {{- if .Values.kcm.kof.acl.enabled }}
      httpMethod: "GET"
      oauthPassThru: true
    {{- end }}
{{- end }}

{{- range .Values.grafana.logSources }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          key: {{ .auth.username_key }}
          name: {{ .auth.credentials_secret_name }}
    - targetPath: "secureJsonData.basicAuthPassword"
      valueFrom:
        secretKeyRef:
          key: {{ .auth.password_key }}
          name: {{ .auth.credentials_secret_name }}
  datasource:
    access: proxy
    isDefault: false
    name: {{ .name }}
    type: {{ .type | default "victoriametrics-logs-datasource" }}
    url: {{ .url }}
    basicAuth: true
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
{{- end }}
{{- end }}
