{{- if .Values.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .Release.Name }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: kof-metrics
    type: prometheus
    access: proxy
    {{- if .Values.kcm.kof.acl.enabled }}
    url: http://{{ .Release.Name }}-kof-acl:{{ .Values.kcm.kof.acl.port }}
    {{- else if .Values.promxy.enabled }}
    url: http://{{ .Release.Name }}-promxy:{{ .Values.promxy.service.servicePort }}
    {{- else }}
    url: http://vmselect-cluster:8481/select/0/prometheus
    {{- end }}
    isDefault: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
    {{- if .Values.kcm.kof.acl.enabled }}
      httpMethod: "GET"
      oauthPassThru: true
    {{- end }}
{{- end }}
